version: 0.0
os: linux
files:
    - source: geodesy-web-services.war
      destination: /usr/share/tomcat8/webapps
hooks:
  ApplicationStop:
    - location: application-stop.sh
  AfterInstall:
    - location: after-install.sh
  ApplicationStart:
    - location: application-start.sh
